version: "3.8"

services:
  backend:
    build:
      context: ./back # Dirección al directorio del back-end
    ports:
      - "3000:3000" # Asigna el puerto 3000 en tu máquina al 3000 del contenedor
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgresql://postgres.rvkyjpmbtxreuiqibtqu:Administrador123@aws-0-us-east-2.pooler.supabase.com:5432/postgres
      - JWT_SECRET=Admin123

networks:
  app-network:
    driver: bridge
