export const seedInhumados = [
  {
    id: '1',
    apellido: 'Álvarez',
    nombre: 'Antonio Carlos',
    fnac: '1 de Enero de 1940',
    ffal: '12 de Marzo de 1992',
    valle: 'Los Pinos',
    sector: '-',
    manzana: 2,
    parcela: 10,
    simbolo: 1,
    ncliente: 101,
  },
  {
    id: '2',
    apellido: 'Barrera',
    nombre: 'Beatriz Elena',
    fnac: '15 de Mayo de 1955',
    ffal: '22 de Octubre de 2005',
    valle: 'Nogales',
    sector: '-',
    manzana: 3,
    parcela: 12,
    simbolo: 1,
    ncliente: 102,
  },
  {
    id: '3',
    apellido: 'Cabrera',
    nombre: 'Carlos Alberto',
    fnac: '30 de Octubre de 1932',
    ffal: '1 de Julio de 2000',
    valle: 'Robles',
    sector: '-',
    manzana: 4,
    parcela: 14,
    simbolo: 1,
    ncliente: 103,
  },
  {
    id: '4',
    apellido: 'Domínguez',
    nombre: 'David Ernesto',
    fnac: '4 de Julio de 1945',
    ffal: '18 de Noviembre de 2012',
    valle: 'Los Olivos',
    sector: '-',
    manzana: 5,
    parcela: 20,
    simbolo: 1,
    ncliente: 104,
  },
  {
    id: '5',
    apellido: 'Espinosa',
    nombre: 'Eduardo Felipe',
    fnac: '10 de Marzo de 1958',
    ffal: '25 de Mayo de 2016',
    valle: 'Cypress',
    sector: '-',
    manzana: 6,
    parcela: 23,
    simbolo: 1,
    ncliente: 105,
  },
  {
    id: '6',
    apellido: 'Figueroa',
    nombre: 'Fernanda Isabel',
    fnac: '23 de Agosto de 1923',
    ffal: '13 de Septiembre de 1988',
    valle: 'Robles',
    sector: '-',
    manzana: 7,
    parcela: 30,
    simbolo: 1,
    ncliente: 106,
  },
  {
    id: '7',
    apellido: 'González',
    nombre: 'Guillermo Iván',
    fnac: '12 de Diciembre de 1937',
    ffal: '30 de Enero de 2005',
    valle: 'Nogales',
    sector: '-',
    manzana: 8,
    parcela: 35,
    simbolo: 1,
    ncliente: 107,
  },
  {
    id: '8',
    apellido: 'Herrera',
    nombre: 'Héctor Manuel',
    fnac: '27 de Junio de 1965',
    ffal: '9 de Octubre de 2020',
    valle: 'Olivos',
    sector: '-',
    manzana: 9,
    parcela: 40,
    simbolo: 1,
    ncliente: 108,
  },
  {
    id: '9',
    apellido: 'Iglesias',
    nombre: 'Ismael Alejandro',
    fnac: '16 de Febrero de 1928',
    ffal: '14 de Julio de 1995',
    valle: 'Robles',
    sector: '-',
    manzana: 10,
    parcela: 45,
    simbolo: 1,
    ncliente: 109,
  },
  {
    id: '10',
    apellido: 'Jiménez',
    nombre: 'José Luis',
    fnac: '21 de Septiembre de 1934',
    ffal: '3 de Enero de 2009',
    valle: 'Los Pinos',
    sector: '-',
    manzana: 11,
    parcela: 50,
    simbolo: 1,
    ncliente: 110,
  },
  {
    id: '11',
    apellido: 'Klein',
    nombre: 'Karla Gabriela',
    fnac: '9 de Octubre de 1943',
    ffal: '12 de Noviembre de 1999',
    valle: 'Cypress',
    sector: '-',
    manzana: 12,
    parcela: 55,
    simbolo: 1,
    ncliente: 111,
  },
  {
    id: '12',
    apellido: 'López',
    nombre: 'Luis Eduardo',
    fnac: '3 de Abril de 1952',
    ffal: '19 de Julio de 2010',
    valle: 'Nogales',
    sector: '-',
    manzana: 13,
    parcela: 60,
    simbolo: 1,
    ncliente: 112,
  },
  {
    id: '13',
    apellido: 'Martínez',
    nombre: 'Marta Beatriz',
    fnac: '22 de Noviembre de 1930',
    ffal: '15 de Octubre de 2015',
    valle: 'Robles',
    sector: '-',
    manzana: 14,
    parcela: 65,
    simbolo: 1,
    ncliente: 113,
  },
  {
    id: '14',
    apellido: 'Núñez',
    nombre: 'Norberto Mario',
    fnac: '10 de Enero de 1949',
    ffal: '8 de Febrero de 2018',
    valle: 'Olivos',
    sector: '-',
    manzana: 15,
    parcela: 70,
    simbolo: 1,
    ncliente: 114,
  },
  {
    id: '15',
    apellido: 'Orozco',
    nombre: 'Oscar Javier',
    fnac: '18 de Mayo de 1954',
    ffal: '25 de Marzo de 2006',
    valle: 'Los Pinos',
    sector: '-',
    manzana: 16,
    parcela: 75,
    simbolo: 1,
    ncliente: 115,
  },
  {
    id: '16',
    apellido: 'Paredes',
    nombre: 'Patricia Rosa',
    fnac: '28 de Septiembre de 1937',
    ffal: '11 de Mayo de 2007',
    valle: 'Cypress',
    sector: '-',
    manzana: 17,
    parcela: 80,
    simbolo: 1,
    ncliente: 116,
  },
  {
    id: '17',
    apellido: 'Quintero',
    nombre: 'Quintín Ernesto',
    fnac: '5 de Diciembre de 1940',
    ffal: '22 de Junio de 2012',
    valle: 'Nogales',
    sector: '-',
    manzana: 18,
    parcela: 85,
    simbolo: 1,
    ncliente: 117,
  },
  {
    id: '18',
    apellido: 'Ramírez',
    nombre: 'Raúl Augusto',
    fnac: '2 de Marzo de 1926',
    ffal: '27 de Agosto de 1997',
    valle: 'Robles',
    sector: '-',
    manzana: 19,
    parcela: 90,
    simbolo: 1,
    ncliente: 118,
  },
  {
    id: '19',
    apellido: 'Sánchez',
    nombre: 'Sara Isabel',
    fnac: '11 de Julio de 1944',
    ffal: '5 de Septiembre de 2010',
    valle: 'Olivos',
    sector: '-',
    manzana: 20,
    parcela: 95,
    simbolo: 1,
    ncliente: 119,
  },
  {
    id: '20',
    apellido: 'Tello',
    nombre: 'Tomás Enrique',
    fnac: '13 de Septiembre de 1920',
    ffal: '8 de Octubre de 1990',
    valle: 'Los Pinos',
    sector: '-',
    manzana: 21,
    parcela: 100,
    simbolo: 1,
    ncliente: 120,
  },
  {
    id: '21',
    apellido: 'Vega',
    nombre: 'Valeria Emilia',
    fnac: '5 de Febrero de 1957',
    ffal: '1 de Enero de 2013',
    valle: 'Cypress',
    sector: '-',
    manzana: 22,
    parcela: 105,
    simbolo: 1,
    ncliente: 121,
  },
  {
    id: '22',
    apellido: 'Wright',
    nombre: 'Walter Hugo',
    fnac: '25 de Agosto de 1942',
    ffal: '20 de Abril de 2017',
    valle: 'Nogales',
    sector: '-',
    manzana: 23,
    parcela: 110,
    simbolo: 1,
    ncliente: 122,
  },
  {
    id: '23',
    apellido: 'Ximénez',
    nombre: 'Ximena Lucía',
    fnac: '14 de Marzo de 1956',
    ffal: '10 de Diciembre de 2018',
    valle: 'Olivos',
    sector: '-',
    manzana: 24,
    parcela: 115,
    simbolo: 1,
    ncliente: 123,
  },
  {
    id: '24',
    apellido: 'Yáñez',
    nombre: 'Yolanda María',
    fnac: '22 de Junio de 1949',
    ffal: '18 de Marzo de 2002',
    valle: 'Robles',
    sector: '-',
    manzana: 25,
    parcela: 120,
    simbolo: 1,
    ncliente: 124,
  },
  {
    id: '25',
    apellido: 'Zúñiga',
    nombre: 'Zacarías Manuel',
    fnac: '17 de Septiembre de 1950',
    ffal: '12 de Octubre de 2011',
    valle: 'Los Pinos',
    sector: '-',
    manzana: 26,
    parcela: 125,
    simbolo: 1,
    ncliente: 125,
  },
  {
    id: '26',
    apellido: 'Cabrera',
    nombre: 'Claudia María',
    fnac: '10 de Abril de 1970',
    ffal: '24 de Marzo de 2022',
    valle: 'Cypress',
    sector: '-',
    manzana: 27,
    parcela: 130,
    simbolo: 1,
    ncliente: 126,
  },
  {
    id: '27',
    apellido: 'Gómez',
    nombre: 'Gerardo Antonio',
    fnac: '21 de Agosto de 1960',
    ffal: '15 de Octubre de 2023',
    valle: 'Olivos',
    sector: '-',
    manzana: 28,
    parcela: 135,
    simbolo: 1,
    ncliente: 127,
  },
  {
    id: '28',
    apellido: 'Mendoza',
    nombre: 'Mariana Lucía',
    fnac: '9 de Febrero de 1981',
    ffal: '5 de Noviembre de 2019',
    valle: 'Los Pinos',
    sector: '-',
    manzana: 29,
    parcela: 140,
    simbolo: 1,
    ncliente: 128,
  },
  {
    id: '29',
    apellido: 'Sierra',
    nombre: 'Santiago Javier',
    fnac: '27 de Julio de 1953',
    ffal: '20 de Marzo de 2015',
    valle: 'Robles',
    sector: '-',
    manzana: 30,
    parcela: 145,
    simbolo: 1,
    ncliente: 129,
  },
  {
    id: '30',
    apellido: 'Torres',
    nombre: 'Tania Isabel',
    fnac: '16 de Enero de 1980',
    ffal: '3 de Abril de 2020',
    valle: 'Cypress',
    sector: '-',
    manzana: 31,
    parcela: 150,
    simbolo: 1,
    ncliente: 130,
  },
];
